# Generated by Django 5.0.6 on 2026-05-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='transport_kind',
            field=models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('plane', 'Plane'), ('ship', 'Ship/Launch'), ('metro', 'Metro Rail')], max_length=10),
        ),
    ]
