# Generated by Django 5.0.6 on 2026-05-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_providerprofile_transport_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('provider', 'Service Provider'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
