# Generated by Django 5.0.6 on 2026-05-01 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('distance_km', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['origin', 'destination'],
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('plane', 'Plane'), ('ship', 'Ship/Launch')], max_length=10)),
                ('code', models.CharField(blank=True, max_length=64, unique=True)),
                ('name', models.CharField(help_text='e.g. Volvo AC, Sundarban Express', max_length=120)),
                ('registration_no', models.CharField(blank=True, max_length=60)),
                ('total_seats', models.PositiveIntegerField(default=40)),
                ('seats_per_row', models.PositiveIntegerField(default=4)),
                ('has_vip_section', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transports/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='accounts.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vip_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='accounts.driverprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transports.route')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transports.transport')),
            ],
            options={
                'ordering': ['departure'],
            },
        ),
    ]
