# Generated by Django 5.0.6 on 2026-05-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_alter_transport_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='bus_type',
            field=models.CharField(blank=True, choices=[('ac', 'AC Bus'), ('non_ac', 'Non-AC Bus'), ('sleeper', 'Sleeper'), ('hyundai', 'Hyundai Bus')], help_text='Only used when kind = bus', max_length=20),
        ),
    ]
