# Generated by Django 5.0.6 on 2026-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_transport_bus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='bus_type',
            field=models.CharField(blank=True, choices=[('ac', 'AC'), ('non_ac', 'Non AC'), ('sleeper', 'Sleeper'), ('hyundai', 'Hyundai')], help_text='Only used when kind = bus', max_length=20),
        ),
    ]
