# Generated by Django 5.0.6 on 2026-05-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_alter_transport_bus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='series_id',
            field=models.CharField(blank=True, db_index=True, help_text='Shared across all schedules from one recurring publish', max_length=32),
        ),
    ]
