# Generated by Django 5.0.6 on 2026-05-01 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('speed_kmh', models.FloatField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='transports.transport')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
